# https://skaffold.dev/docs/references/yaml/
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: go-api
build:
  artifacts:
  - image: go-api
    hooks:
      before:
        - command:
            - bash
            - -c
            - swag init --dir ./src/internal -g app/app.go --parseInternal --parseDependency --output ./src/internal/docs
          os: [darwin, linux]
    ko:
      fromImage: alpine # golang:1.19-alpine
      dir: src/cmd/app
      dependencies:
        paths:
        - "src/*"
        - "skaffold/*"
        - "skaffold.yaml"
        ignore: []
deploy:
  kubectl:
    manifests:
      - skaffold/app.yaml
portForward:
  - resourceType: service
    resourceName: go-api
    port: 80
    address: 127.0.0.1
    localPort: 8080
